name: openwpm
channels:
    - conda-forge
dependencies:
    - python=3.7
    - beautifulsoup4
    - geckodriver
    - leveldb
    - make
    - multiprocess
    - nodejs
    - pandas
    - pillow
    - pip
    - psutil
    - pyarrow
    - python-dateutil
    - selenium
    - s3fs
    - tabulate
    - tblib
    - pip:
        - publicsuffix
        - plyvel
        - mini-amf
